using UnityEngine;
using UnityEngine.UI;
using System.Collections;
/** \class TurinTestAnswerQuestionary
 *  \brief  Handles the Turing Test Questionary answer by checking which group was chosen.
 */
public class TurinTestAnswerQuestionary : Questionary {

	/**
     *  At initialization of script, saves the name of the group generated by the GA
     *  Use this for initialization
     */
	void Start () {

		transform.FindChild("GroupName").GetComponent<Text>().text = GameData.Instance.GetGeneratedGroupName();
	}
}
